dschoenbauer/orm

- src/Orm/Events/Validate/DataType/ValidateDate.php
@dschoenbauer requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/dschoenbauer/orm/
> Scrutinizer Auto-Fixes

- src/Orm/Builder/PdoModelBuilder.php
- src/Orm/Events/Validate/Schema/RemoveId.php
- tests/src/Orm/Builder/PdoModelBuilderTest.php
- tests/src/Orm/Events/Validate/Schema/RemoveIdTest.php
Fixes #33 
- Added remove id validation
- Added remove id validation to PDO Model
---- place an X confirming all items have been verified ----
[X]  Unit tests coverage exceeds or maintains current levels
[X]  Code Sniffer has reported zero issues (run command: ```composer inspect```)
[X]  Documentation is thorough and rich in content
> Feature/33 remove Id

- tests/src/Orm/Builder/ModelDirectorTest.php
- tests/src/Orm/CrudModelTest.php
- tests/src/Orm/Entity/AbstractEntityTest.php
- tests/src/Orm/Events/AbstractEventTest.php
- tests/src/Orm/Events/Persistence/PdoCreateTest.php
- tests/src/Orm/Events/Persistence/PdoDeleteTest.php
- tests/src/Orm/Events/Persistence/PdoSelectTest.php
- tests/src/Orm/Events/Persistence/PdoUpdateTest.php
- tests/src/Orm/Events/Validate/AbstractValidateTest.php
- tests/src/Orm/Events/Validate/DataType/AbstractDataTypeTest.php
- tests/src/Orm/Events/Validate/DataType/DataTypeBooleanTest.php
- tests/src/Orm/Events/Validate/DataType/DataTypeDateTest.php
- tests/src/Orm/Events/Validate/DataType/DataTypeNumberTest.php
- tests/src/Orm/Events/Validate/DataType/DataTypeStringTest.php
- tests/src/Orm/Events/Validate/Schema/DefaultValueTest.php
- tests/src/Orm/Events/Validate/Schema/RemoveIdTest.php
- tests/src/Orm/Events/Validate/Schema/RequiredFieldsTest.php
- tests/src/Orm/Events/Validate/Schema/ValidFieldsTest.php
- tests/src/Orm/Exception/InvalidDataTypeExceptionTest.php
- tests/src/Orm/Exception/RequiredFieldMissingExceptionTest.php
- tests/src/Orm/Framework/AttributeCollectionTest.php
- tests/src/Orm/Framework/AttributeTest.php
- tests/src/Orm/ModelTest.php
Fixes #36
- Updates TestCase name space the the PSR4 standard.
---- place an X confirming all items have been verified ----
[X]  Unit tests coverage exceeds or maintains current levels
[X]  Code Sniffer has reported zero issues (run command: ```composer inspect```)
[X]  Documentation is thorough and rich in content
> Updated all unit tests to use the PSR4 Test Case

- src/Orm/Events/AbstractEvent.php
- src/Orm/Events/Persistence/PdoCreate.php
- src/Orm/Events/Persistence/PdoDelete.php
- src/Orm/Events/Persistence/PdoSelect.php
- src/Orm/Events/Persistence/PdoUpdate.php
- src/Orm/Events/Validate/AbstractValidate.php
- src/Orm/Events/Validate/Schema/RemoveId.php
- tests/src/Orm/Events/Persistence/PdoCreateTest.php
- tests/src/Orm/Events/Persistence/PdoDeleteTest.php
- tests/src/Orm/Events/Persistence/PdoSelectTest.php
- tests/src/Orm/Events/Persistence/PdoUpdateTest.php
- tests/src/Orm/Events/Validate/AbstractValidateTest.php
- tests/src/Orm/Events/Validate/DataType/AbstractDataTypeTest.php
- tests/src/Orm/Events/Validate/Schema/RemoveIdTest.php
Fixes #37
-Exchanged all references to Event for EventInterface giving the program more flexibility
---- place an X confirming all items have been verified ----
[X]  Unit tests coverage exceeds or maintains current levels
[X]  Code Sniffer has reported zero issues (run command: ```composer inspect```)
[X]  Documentation is thorough and rich in content
> Replaced references of Event to EventInterface

- src/Orm/Builder/PdoModelBuilder.php
- src/Orm/Entity/HasFieldAliases.php
- src/Orm/Events/Validate/Schema/AliasEntityCollection.php
- src/Orm/Events/Validate/Schema/AliasEntitySingle.php
- tests/src/Orm/Builder/PdoModelBuilderTest.php
- tests/src/Orm/Events/Validate/Schema/AliasEntityCollectionTest.php
- tests/src/Orm/Events/Validate/Schema/AliasEntitySingleTest.php
Fixes #31
-Adds a process for renaming fields passed to and from the API
---- place an X confirming all items have been verified ----
[X]  Unit tests coverage exceeds or maintains current levels
[X]  Code Sniffer has reported zero issues (run command: ```composer inspect```)
[X]  Documentation is thorough and rich in content
> add in entity defined aliases

- .github/PULL_REQUEST_TEMPLATE.md
> Updated PULL_REQUEST_TEMPLATE

- src/Orm/Events/Validate/Schema/StaticValue.php
- tests/src/Orm/Events/Validate/Schema/StaticValueTest.php
Fixes #29
-Added new static value filter
> Added static value filter to ORM

- .travis.yml
Fixes #51 
-Adds remote data push for coverage
> Updated looking for new coverage

- composer.lock
- src/Orm/Builder/ModelDirector.php
- src/Orm/Events/Persistence/Pdo/Select.php
Fixes #53
Fixes #57 
- Updated PDO events to a separate name space
- Updated Filter classes (do they need their own abstract specific to them? Time will tell)
> Updated Filters and PDO

- src/Orm/Builder/PdoModelBuilder.php
- src/Orm/Events/Framework/CrossTrigger.php
- src/Orm/ModelInterface.php
- tests/src/Orm/Builder/PdoModelBuilderTest.php
- tests/src/Orm/Events/Framework/CrossTriggerTest.php
Fixes #61 
- Adds new cross trigger event to trigger other events
> Added in new cross trigger event

- composer.json
- composer.lock
- src/Orm/Entity/MassMappingInterface.php
- src/Orm/Events/Filter/MassMapper.php
- tests/src/Orm/Events/Filter/MassMapperTest.php
Fixes #59
- Adds new mass mapper to project
- allows for data changes in schema
> Added mass mapper

- src/Orm/Builder/AbstractBuilder.php
- src/Orm/Builder/RestModelBuilder.php
- tests/src/Orm/Builder/AbstractBuilderTest.php
- tests/src/Orm/Builder/RestModelBuilderTest.php
Fixes #64
-Adds a Rest Model Builder
-Split PDO builder into an Abstract Build and a PDO builder
> Added a rest model builder

- src/Orm/Builder/AbstractBuilder.php
- tests/src/Orm/Builder/AbstractBuilderTest.php
Fixes #64
-Corrected missing interface on the new abstract
> Corrected missing interface

- src/Orm/Builder/Component/FilePersistence.php
- tests/src/Orm/Builder/Component/FilePersistenceTest.php
task: #74
Fixes #74 
- Adds new File Persistence builder that adds necessary events for persisting to a file.
> Add component to allow easier use of file persistence

- src/Orm/Exception/InvalidXmlException.php
- src/Orm/Framework/XmlToArrayParser.php
- tests/files/xml/attribute.json
- tests/files/xml/attribute.xml
- tests/files/xml/basic.json
- tests/files/xml/basic.xml
- tests/files/xml/complex.json
- tests/files/xml/complex.xml
- tests/files/xml/error.xml
- tests/src/Orm/Events/Framework/XmlToArrayParserTest.php
- tests/src/Orm/Exception/InvalidXmlExceptionTest.php
task: #76
Fixes #76 
- adds XML parser
> Add new xml parser to library

- composer.lock
- index.php
- src/Orm/Events/Filter/DataType/BooleanFilter.php
- tests/src/Orm/Events/Filter/DataType/BooleanFilterTest.php
> add capability to boolean filter to change results

- src/Orm/Events/Filter/DataType/BooleanFilter.php
- tests/src/Orm/Events/Filter/DataType/BooleanFilterTest.php
> Add missing constructor arguments

- src/Orm/Events/Filter/DataType/BooleanFilter.php
Updated file format
Fixes #78
- Updated layout to meet PSR-2 standards
> Update formatting of code to comply with PS2

- src/Orm/Entity/HasFieldsToRemove.php
- src/Orm/Entity/HasFieldsToRemoveInterface.php
- src/Orm/Events/Filter/RemoveFields.php
- tests/src/Orm/Events/Filter/RemoveFieldsTest.php
task: #106
Fixes #106 
- Creates a new filter event that removes fields as defined by the HasFieldsToRemoveInterface
> Add remove fields filter

- src/Orm/Events/Filter/RemoveFields.php
- tests/src/Orm/Events/Filter/RemoveFieldsTest.php
task: #117
Fixes #117 
- Change remove fields method to purge fields to reduce confusion around constructor
> Update remove fields event so constructor is clear

- src/Orm/Entity/HasUniqueFieldsInterface.php
- src/Orm/Events/Validate/Schema/UniqueFields.php
- src/Orm/Exception/NonUniqueValueException.php
- tests/src/Orm/Events/Validate/Schema/UniqueFieldsTest.php
- tests/src/Orm/Exception/NonUniqueValueExceptionTest.php
task: #105
Fixes #105
- Add an event that checks given fields to be unique
> Complete the addition of unique value event

- src/Orm/Framework/XmlToArrayParser.php
task: #118
Fixes #118 
-Improve XML code readability
> Updated XML Parser to improve readability

- src/Orm/Framework/XmlToArrayParser.php
task: #118
Fixes #118 
- Final Update
-
-
-
> Remove unused code

- src/Orm/Events/Guard/GuardEvent.php
- src/Orm/Events/Guard/GuardInterface.php
- tests/src/Orm/Events/Guard/GuardEventTest.php
task: #134
Fixes #134
- Adds Guard Process to library
> Add Guard process to library

- composer.lock
- src/Orm/Events/Logger/DebugLog.php
- tests/configuration.xml
- tests/src/Orm/Events/Logger/DebugLogTest.php
task: #143
Fixes #143
- Adds debug log event
-
-
-
> Add Debug Log Event

- src/Orm/Events/Logger/ErrorLog.php
- src/Orm/Events/Validate/AbstractValidate.php
> Correct scrutinizer issue

- src/Orm/DataProvider/DataEmbedderManyToMany.php
- tests/src/Orm/DataProvider/DataEmbedderManyToManyTest.php
task: #162
Fixes #1624
- Adds new data provider data em-bedder to handle a many to many scenario
> Add many to many data embedder

- src/Orm/CrudModel.php
- src/Orm/Enum/EventParameters.php
- tests/src/Orm/CrudModelTest.php
> Update Crud Model To Not Capture exceptions

- src/Orm/Events/Filter/PasswordValidate.php
- tests/src/Orm/Events/Filter/PasswordValidateTest.php
task: #177
Fixes #177
- Update model id with the user ID when user validates
> Update password validate to update id field

- src/Orm/Events/Filter/PasswordValidate.php
- tests/src/Orm/Events/Filter/PasswordValidateTest.php
task: #177
Fixes #177
- Update fields being returned.
> Correct fields 
